FROM node:10

# set up container to create files with your current user
ARG USER_ID
ARG GROUP_ID
RUN groupmod -g 999 node && usermod -u 999 -g 999 node
RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user

# install node_modules in different folder and point node to it (image portability)
# WORKDIR /nm
# COPY ./package*.json /nm/
# RUN npm install
# ENV NODE_PATH=/nm/node_modules
# change file ownership so you can install more packages as you develop
# RUN chown -R user:user /nm

# USER user

# main working directory
WORKDIR /app/client/
COPY ./package*.json /app/client/
RUN npm install

# Add rest of the client code
COPY . /app/client/

EXPOSE 3000

CMD npm start
