export const blankClient = {
    abonado: "",
    name: "",
    telefono: "",
    email: "",
    address: {
        street: "",
        apto: "",
        location: "",
        city: ""
    },
    services: [],
    hardware: [],
    pm: "",
    im: "",
    status: "Implementacion",
    validation: {
        abonado: { valid: false, invalid: false, message: '', editable: true }
    },
    hideEditButton: true,
    search: ""
}

export const serviceBlankState = {
  service: '',
  plan: '',
  medium: '',
  red: '',
  ip: '',
  dg: '',
  mask: '',
  vlan: '',
  ip_mon: '10.252.',
  ip_mon_router: '10.252',
  dg_mon: '10.252',
  mask_mon: '255.255.255.',
  vlan_mon: '152',
  lan_red: '',
  lan_ip: '',
  lan_dg: '',
  lan_mask: '',
  mode: '',
  sites: {hub: '', spokes: ''},
  device: '',
  device_router: '',
  nhead: '112120',
  ntale: '112120',
  hub: '',
  obra: '',
  rack: '',
  patchera: '',
  position: '',
  nexus: 'N93180-',
  nexus_port: '',
  dist: '',
  att: '',
  cmts: '',
  mac: '',
  interface: 'G1',
  interface_router: '',
  pm: '',
  im: '',
  status: 'Init',
};
